version: "2"
services:
  httpd:
    image: ulsmith/alpine-apache-php7
    working_dir: /app
    ports:
      - 80:80
    volumes:
      - .:/app:cached
    links:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379