#!/usr/bin/env php

<?php

use App\Controller;
use App\HttpClient\PayloadFactory;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/bootstrap.php';

foreach (explode(',', getenv('WATCHING_PROJECTS')) as $projectId) {
    PayloadFactory::setId($projectId);

    $container->call(Controller::class . "::handle", [
        'id' => $projectId,
    ]);
}
