#!/usr/bin/env php

<?php

use App\Project;
use App\Setting;
use App\Controller;
use App\HttpClient\HttpClient;
use App\HttpClient\Project as ProjectPayload;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/bootstrap.php';

foreach (Setting::getProjects() as $projectId) {

    $project = $container->get(HttpClient::class)->send(new ProjectPayload($projectId));
    Project::set($project);

    $container->call(Controller::class . "::handle", [
        'id' => $projectId,
    ]);
}
